version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/production/php/Dockerfile
    platform: linux/x86_64

  web:
    build:
      context: .
      dockerfile: ./infra/docker/production/nginx/Dockerfile
    platform: linux/x86_64
